### ISSUE TITLE
Bug: take in account * in schema filenames

### ISSUE THREAD

**Issue by nvuillam** [chris48s/v8r#4] opened 2020-12-19 09:44 UTC
Some schemas contain fileMatch with * caracter

Example:
![image](https://user-images.githubusercontent.com/17500430/102686285-cfd41b80-41e6-11eb-8cd0-8cfe2f43df45.png)

v8r only checks for identical file name

To reproduce:
`v8r json_good_1.cf.json`

Cloudformation schema should be found but is not:

`❌ Could not find a schema to validate json_good_1.cf.json`

**Comment by chris48s** [comment] 2020-12-19 15:36
This is a duplicate of #1. `*.cf.json` is a glob pattern

**Closed by chris48s** 2020-12-19 15:36 UTC
